### PR TITLE
feat(players): players by country

### PR DESCRIPTION
**Pull request by j-masci**
A first pass at a players by country page. A lot of small things could be improved but let's just call this a working, stable beta for now. Overall I really like the page and its useful. Biggest downside perhaps is that the ranking system I think is only about a year old, so players that haven't played since then get put to bottom of the list it seems.

How it works:
Open the page and a list of countries is shown with players within each country. Countries have several sorting options to show most relevant countries at top. The number of players shown in each list has several options including showing all ranked and all players.

Possible future additions:
- make run faster. However, no unnecessary renders or sorts (should be) / are being performed. However, there are a ton of players and sorting is quite slow. Sorting is done in client. The server only provides the full list of players as it used to.
- countries near bottom of list, without any ranked players show no players by default (could be improved)
- options to sort players within each country (right now its always by battle ranking)
- linking things to other things
- add more columns? I wonder what data would be interesting to show
- table columns could be centered
- remove hover effect and/or make entire row link to player. right now have to click players name.

Regarding components/List
- I only passed the className prop a long to each item so I could add custom border style. The code diff looks large but only because I put the exported functions in a more logical order.

### CODE REVIEW

**Comment by j-masci** [comment]
Requires this: https://github.com/elmadev/elmaonline-site/pull/414


https://user-images.githubusercontent.com/24510397/113524788-00b24380-957f-11eb-96bc-1246368f041b.mp4

**Comment by j-masci** [comment]
Player sort, ranked players only switch, and link to designed battles.

Country sort also has option to sort by whatever players are sorted by (dynamically so to speak). You can do some cool things like easily find TL at the top of the list.

https://user-images.githubusercontent.com/24510397/113534322-695ce880-959e-11eb-835b-987a59a97759.mp4

**Review by j-masci — COMMENTED** [review]
I should prolly undelete the config file. Don't understand.. did git rm --cached.

**Comment by j-masci** [comment]
> I should prolly undelete the config file. Don't understand.. did git rm --cached.

fixed now. not sure how this happened (thank you git)

**Review by sunehs — APPROVED** [review]

**Comment by sunehs** [comment]
is pos then make branches in the main repo, it wouldn't let me checkout from your fork so had to merge to test

I fixed win percent calculation, fyi winsAll counts battles with 5+ players and playedAll counts all battles, so you need played5All for proper calculation

thought the query would be slow with both where and sort by that's unindexed but it's pretty fast on live as well :>

**Comment by j-masci** [comment]
Cool stuff thank you :) Will start pushing branches to main repo.

**Pull request merged**
