### PR TITLE
play stats tabs for level packs and cups

### PR DESCRIPTION
**Pull request by j-masci**
Adds 2 new pages...

Level pack play stats, and Cup play stats.

I didn't put too much thought into the stats or how they are displayed for now (just lots of "popularity" bars). But we could modify some things later.

image

image

### CODE REVIEW

**Comment by j-masci** [comment]
For battle ranking card...

reduced column widths and added minimum width to the table so that if a scrollbar is present the columns still line up properly. On desktop, the table actually looks a bit worse because the name column is larger and the other columns smaller, but it makes things work a lot nice on any smaller screens.

image

image

**Comment by j-masci** [comment]
Added max-height and possible scrollbar to replay list on level page, since some internals now have hundreds of replays.

image

**Comment by j-masci** [comment]
In one of the earlier commits I made these buttons just a bit larger.. they were previously pretty challenging to click on mobile without accidentally clicking the replay file :)

image

**Comment by j-masci** [comment]
Added a link to the homepage events widget to go directly to the previous events replays page.

image

**Review by sunehs — APPROVED** [review]

**Pull request merged**
